# Generated by Django 6.0.6 on 2026-06-05 13:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="名称")),
                (
                    "identifier",
                    models.CharField(
                        db_index=True, max_length=12, verbose_name="标识符"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                (
                    "is_archived",
                    models.BooleanField(default=False, verbose_name="已归档"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="led_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="项目负责人",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="workspaces.workspace",
                        verbose_name="工作空间",
                    ),
                ),
            ],
            options={
                "verbose_name": "项目",
                "verbose_name_plural": "项目",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "管理员"),
                            ("member", "普通成员"),
                            ("viewer", "只读"),
                        ],
                        default="member",
                        max_length=20,
                        verbose_name="角色",
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="projects.project",
                        verbose_name="项目",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "项目成员",
                "verbose_name_plural": "项目成员",
            },
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["workspace", "is_archived"],
                name="projects_pr_workspa_66e648_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="project",
            unique_together={("workspace", "identifier")},
        ),
        migrations.AlterUniqueTogether(
            name="projectmember",
            unique_together={("project", "user")},
        ),
    ]
