# Generated by Django 6.0.6 on 2026-06-05 13:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("iterations", "0001_initial"),
        ("modules", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="名称")),
                (
                    "color",
                    models.CharField(
                        default="#6366f1", max_length=7, verbose_name="颜色"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="排序")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("backlog", "待办"),
                            ("unstarted", "未开始"),
                            ("started", "进行中"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="unstarted",
                        max_length=20,
                        verbose_name="类型",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_statuses",
                        to="projects.project",
                        verbose_name="项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "任务状态",
                "verbose_name_plural": "任务状态",
                "ordering": ["order"],
                "unique_together": {("project", "name")},
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="标题")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("urgent", "紧急"),
                            ("high", "高"),
                            ("medium", "中"),
                            ("low", "低"),
                            ("none", "无"),
                        ],
                        default="none",
                        max_length=10,
                        verbose_name="优先级",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="截止日期"),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="开始日期"),
                ),
                ("order", models.FloatField(default=0.0, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="负责人",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "iteration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="iterations.iteration",
                        verbose_name="迭代",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="modules.module",
                        verbose_name="模块",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtasks",
                        to="tasks.task",
                        verbose_name="父任务",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="projects.project",
                        verbose_name="项目",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tasks",
                        to="tasks.taskstatus",
                        verbose_name="状态",
                    ),
                ),
            ],
            options={
                "verbose_name": "任务",
                "verbose_name_plural": "任务",
                "ordering": ["order", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "status"],
                        name="tasks_task_project_d48c46_idx",
                    ),
                    models.Index(
                        fields=["project", "assignee"],
                        name="tasks_task_project_5e8812_idx",
                    ),
                    models.Index(
                        fields=["project", "priority"],
                        name="tasks_task_project_7f8813_idx",
                    ),
                    models.Index(
                        fields=["project", "iteration"],
                        name="tasks_task_project_ef6e43_idx",
                    ),
                    models.Index(
                        fields=["due_date"], name="tasks_task_due_dat_bce847_idx"
                    ),
                ],
            },
        ),
    ]
